### ISSUE TITLE
How i make connect to memcache via socket?

### ISSUE THREAD

**Issue by Satariall** [lagged/memcache.php#1]
Now i write default path `unix:///var/run/memcached.sock` and script wrote 'cant connect ...'

**Comment by gejobj** [comment]
Hello.

I made these changes to sendMemcacheCommands function at src/functions.php:

<pre>
<code>
function sendMemcacheCommands($command){
        $result = array();
        foreach($GLOBALS['MEMCACHE_SERVERS'] as $server){
                if ( strstr($server, 'unix:') === false ){
                        list($host, $port) = explode(':', $server);
                } else {
                        $host=$server;
                        $port=-1;
                }
                $result[$server]   = sendMemcacheCommand($host,$port,$command);
        }
        return $result;
}
</code>
</pre>

And now you can use socket files instead IP:port like this:
$GLOBALS['MEMCACHE_SERVERS'][] = 'unix:///var/pace/to/socket/memcached.sock';

Bye.

**Comment by iBobik** [comment]
Now I found that function sendMemcacheCommand is used in more places than just in sendMemcacheCommands

**Comment by till** [comment]
@iBobik thanks, I merged your PR!
@gejobj Thank you as well.

@Satariall Please try master!

**Comment by Satariall** [comment]
@till 4 years have passed... -) Thank you, I believe that it works.

**Comment by till** [comment]
@Satariall sorry about that. :-)
