### ISSUE TITLE
Cant connect to:127.0.0.1:11211

### ISSUE THREAD

**Issue by PaddyLock** [lagged/memcache.php#5]
I can run the script on my local machine, but when I try and run on my staging server I get the following error message: 

```
Cant connect to:127.0.0.1:11211
```

I have this in my config.php

```
$GLOBALS['MEMCACHE_SERVERS'][] = '127.0.0.1:11211';
```

I don't understand in your readme what you mean by make changes in ect/config.local.php ? this file doesn't exist? do I need to create it in the same folder, and why?

thanks

**Comment by PaddyLock** [comment]
seems to be working fine now

**Comment by PaddyLock** [comment]
I have just done a fresh deploy and now I am experiencing the same problem. I am restarting memcached after deploy.

**Comment by till** [comment]
@PaddyLock likely a problem with your memcache.
